/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ProfileManager;

import java.awt.CardLayout;
import javax.swing.JPanel;
import model.PersonDirectory;

/**
 *
 * @author ayushighia
 */
public class ProfileMngWorkArea extends javax.swing.JPanel {
    JPanel userProcessContainer;
    PersonDirectory personDirectory;

   

    /**
     * Creates new form ProfileMngWorkArea
     * @param Container
     * @param directory
     */
     public ProfileMngWorkArea(JPanel Container, PersonDirectory directory) {
        initComponents ();
        
  
        userProcessContainer= Container;
        personDirectory = directory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btbAddPerson = new javax.swing.JButton();
        btbListPerson = new javax.swing.JButton();
        btbSearch = new javax.swing.JButton();
        txtSearchBar = new javax.swing.JTextField();

        btbAddPerson.setText("Add Person");
        btbAddPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbAddPersonActionPerformed(evt);
            }
        });

        btbListPerson.setText("List Person");
        btbListPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbListPersonActionPerformed(evt);
            }
        });

        btbSearch.setText("Search ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSearchBar)
                        .addGap(3, 3, 3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btbAddPerson)
                        .addComponent(btbListPerson)
                        .addComponent(btbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(389, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(btbAddPerson)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btbListPerson)
                .addGap(72, 72, 72)
                .addComponent(btbSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btbAddPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbAddPersonActionPerformed
        // TODO add your handling code here:
      CreateProfileJPanel panel= new CreateProfileJPanel(userProcessContainer, personDirectory);
      userProcessContainer. add("CreateProfileJPanel", panel);
        
      CardLayout layout = (CardLayout) userProcessContainer.getLayout();
      layout.next(userProcessContainer);
        
        
     
        
        
        
        
        
    }//GEN-LAST:event_btbAddPersonActionPerformed

    private void btbListPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbListPersonActionPerformed
        // TODO add your handling code here:
         ManageProfileJPanel panel;
        panel = new ManageProfileJPanel(userProcessContainer,personDirectory);
        userProcessContainer.add("ViewAccountJPanel", panel);
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        
        
        
        
        
    }//GEN-LAST:event_btbListPersonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbAddPerson;
    private javax.swing.JButton btbListPerson;
    private javax.swing.JButton btbSearch;
    private javax.swing.JTextField txtSearchBar;
    // End of variables declaration//GEN-END:variables

    
    }

